// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_1lOKJ_ur41ncqMw_yBcI8k8aumRTq18',
    appId: '1:631045397300:web:49a3dd9cd8327ae1f6a361',
    messagingSenderId: '631045397300',
    projectId: 'flutter-univ-bingo',
    authDomain: 'flutter-univ-bingo.firebaseapp.com',
    storageBucket: 'flutter-univ-bingo.appspot.com',
    measurementId: 'G-6SXWRVZD7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxoOu9p_VCJIoCKVMs2n3VHMPM8LRtJGM',
    appId: '1:631045397300:android:6a1e57ec88b053c2f6a361',
    messagingSenderId: '631045397300',
    projectId: 'flutter-univ-bingo',
    storageBucket: 'flutter-univ-bingo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAL-PPoEhcZEHDoG65CHV4R8FKbm9eCR8',
    appId: '1:631045397300:ios:8681817b6bbd59e6f6a361',
    messagingSenderId: '631045397300',
    projectId: 'flutter-univ-bingo',
    storageBucket: 'flutter-univ-bingo.appspot.com',
    iosClientId: '631045397300-oigog2e0mn5vse3hved7qas7o1fnbsef.apps.googleusercontent.com',
    iosBundleId: 'com.example.bingo',
  );
}
